name: .NET with SCP and Run

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Publish
      run: dotnet publish -c Release --output out

    - name: Zip Application
      run: zip -r app.zip ./out

    - name: Deploy to Dev using SSH
      env:
        AWS_EC2_PEM: ${{ secrets.AWS_EC2_DEV_PEM }}
        AWS_EC2_PUBLIC_IP: ${{ secrets.AWS_EC2_DEV_PUBLIC_IP }}
        AWS_EC2_USERNAME: ${{ secrets.AWS_EC2_DEV_USERNAME }}
      run: |
        echo "$AWS_EC2_PEM" > private.pem && chmod 600 private.pem
        scp -o StrictHostKeyChecking=no -i private.pem app.zip $AWS_EC2_USERNAME@$AWS_EC2_PUBLIC_IP:/home/ubuntu
        ssh -o StrictHostKeyChecking=no -i private.pem $AWS_EC2_USERNAME@$AWS_EC2_PUBLIC_IP "cd /home/ubuntu && unzip app.zip && dotnet out/BPCalculator.dll"
